language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- TRAVIS_TAG="Deploy-2017.2.0f3" PROJECT_NAME="UnityExamplePackage" UNITY_PROJECT_PATH="UnityExample" DEPLOY_UNITYPACKAGE="path set in deploy script"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- chmod a+x ./travis-build/*.sh

install:
- cat /etc/hosts
- ./travis-build/install-unity.sh

script:
- ./travis-build/build.sh
- ./travis-build/run-tests.sh
- ./travis-build/export-unity-package.sh
- git clone https://github.com/andreafabrizi/Dropbox-Uploader.git
- echo "OAUTH_ACCESS_TOKEN=vp0TyqCJLF0AAAAAAAACLF4EpS8qwQa23nhKzYqhdow0ekBQ4j67HfdRHjDsf8ox" > .dropbox_uploader
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Dropbox-Uploader/dropbox_uploader.sh -f .dropbox_uploader upload ./release/UnityExamplePackage-vDeploy-2017.2.0f3.zip UnityExamplePackage-vDeploy-2017.2.0f3.zip;fi

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true 
